// Code generated by github.com/newclarity/PackageReflect DO NOT EDIT.

package crawler

import "reflect"

var Types = map[string]reflect.Type{
	"Crawler": reflect.TypeOf((*Crawler)(nil)).Elem(),
	"Debugger": reflect.TypeOf((*Debugger)(nil)).Elem(),
}

var Functions = map[string]reflect.Value{
	"NewCrawler": reflect.ValueOf(NewCrawler),
}

var Variables = map[string]reflect.Value{
}

var Consts = map[string]reflect.Value{
	"NoPatternDefined": reflect.ValueOf(NoPatternDefined),
}

