// Code generated by github.com/ungerik/pkgreflect DO NOT EDIT.

package helperService

import "reflect"

var Types = map[string]reflect.Type{
	"HelperService": reflect.TypeOf((*HelperService)(nil)).Elem(),
	"ServiceGetter": reflect.TypeOf((*ServiceGetter)(nil)).Elem(),
	"State": reflect.TypeOf((*State)(nil)).Elem(),
	"TypeService": reflect.TypeOf((*TypeService)(nil)).Elem(),
}

var Functions = map[string]reflect.Value{
	"New": reflect.ValueOf(New),
	"ReflectHelperService": reflect.ValueOf(ReflectHelperService),
}

var Variables = map[string]reflect.Value{
	"GetHelpers": reflect.ValueOf(&GetHelpers),
}

var Consts = map[string]reflect.Value{
	"HelperPrefix": reflect.ValueOf(HelperPrefix),
	"OnlyOnce": reflect.ValueOf(OnlyOnce),
}

