// Code generated by github.com/newclarity/PackageReflect DO NOT EDIT.

package util

import "reflect"

var Types = map[string]reflect.Type{
}

var Functions = map[string]reflect.Value{
	"DirExists": reflect.ValueOf(DirExists),
	"EntryExists": reflect.ValueOf(EntryExists),
	"ExecDir": reflect.ValueOf(ExecDir),
	"FileDir": reflect.ValueOf(FileDir),
	"FileExists": reflect.ValueOf(FileExists),
	"MaybeMakeDir": reflect.ValueOf(MaybeMakeDir),
	"ParentDir": reflect.ValueOf(ParentDir),
	"SecondsDuration": reflect.ValueOf(SecondsDuration),
	"StripWhitespace": reflect.ValueOf(StripWhitespace),
}

var Variables = map[string]reflect.Value{
}

var Consts = map[string]reflect.Value{
}

