// Code generated by github.com/ungerik/pkgreflect DO NOT EDIT.

package toolExample

import "reflect"

var Types = map[string]reflect.Type{
	"ExampleGetter": reflect.TypeOf((*ExampleGetter)(nil)).Elem(),
	"HelperExample": reflect.TypeOf((*HelperExample)(nil)).Elem(),
	"State": reflect.TypeOf((*State)(nil)).Elem(),
	"TypeExample": reflect.TypeOf((*TypeExample)(nil)).Elem(),
}

var Functions = map[string]reflect.Value{
	"New": reflect.ValueOf(New),
	"ReflectHelperExample": reflect.ValueOf(ReflectHelperExample),
}

var Variables = map[string]reflect.Value{
	"GetHelpers": reflect.ValueOf(&GetHelpers),
}

var Consts = map[string]reflect.Value{
	"HelperPrefix": reflect.ValueOf(HelperPrefix),
	"OnlyOnce": reflect.ValueOf(OnlyOnce),
}

