// Code generated by github.com/newclarity/PackageReflect DO NOT EDIT.

package mocks

import "reflect"

var Types = map[string]reflect.Type{
}

var Functions = map[string]reflect.Value{
	"NewConfig": reflect.ValueOf(NewConfig),
}

var Variables = map[string]reflect.Value{
}

var Consts = map[string]reflect.Value{
}

