// Code generated by github.com/newclarity/PackageReflect DO NOT EDIT.

package test

import "reflect"

var Types = map[string]reflect.Type{
	"Config": reflect.TypeOf((*Config)(nil)).Elem(),
}

var Functions = map[string]reflect.Value{
	"CheckErr": reflect.ValueOf(CheckErr),
	"FmtDir": reflect.ValueOf(FmtDir),
	"TestHosts": reflect.ValueOf(TestHosts),
	"TestResources": reflect.ValueOf(TestResources),
}

var Variables = map[string]reflect.Value{
}

var Consts = map[string]reflect.Value{
}

