// Code generated by github.com/newclarity/PackageReflect DO NOT EDIT.

package toolNetwork

import "reflect"

var Types = map[string]reflect.Type{
	"State": reflect.TypeOf((*State)(nil)).Elem(),
	"ToolNetwork": reflect.TypeOf((*ToolNetwork)(nil)).Elem(),
	"TypeNetwork": reflect.TypeOf((*TypeNetwork)(nil)).Elem(),
}

var Functions = map[string]reflect.Value{
	"New": reflect.ValueOf(New),
	"ReflectState": reflect.ValueOf(ReflectState),
	"ReflectToolNetwork": reflect.ValueOf(ReflectToolNetwork),
}

var Variables = map[string]reflect.Value{
	"GetTools": reflect.ValueOf(&GetTools),
}

var Consts = map[string]reflect.Value{
	"ToolPrefix": reflect.ValueOf(ToolPrefix),
}

