// Code generated by github.com/newclarity/PackageReflect DO NOT EDIT.

package algolia

import "reflect"

var Types = map[string]reflect.Type{
	"Algolia": reflect.TypeOf((*Algolia)(nil)).Elem(),
}

var Functions = map[string]reflect.Value{
	"NewAlgolia": reflect.ValueOf(NewAlgolia),
}

var Variables = map[string]reflect.Value{
}

var Consts = map[string]reflect.Value{
}

