// Code generated by github.com/newclarity/PackageReflect DO NOT EDIT.

package log

import "reflect"

var Types = map[string]reflect.Type{
	"Logger": reflect.TypeOf((*Logger)(nil)).Elem(),
}

var Functions = map[string]reflect.Value{
	"NewLogger": reflect.ValueOf(NewLogger),
}

var Variables = map[string]reflect.Value{
}

var Consts = map[string]reflect.Value{
}

