// Code generated by github.com/newclarity/PackageReflect DO NOT EDIT.

package gearSsh

import "reflect"

var Types = map[string]reflect.Type{
	"Environment": reflect.TypeOf((*Environment)(nil)).Elem(),
	"Ssh": reflect.TypeOf((*Ssh)(nil)).Elem(),
	"SshAuth": reflect.TypeOf((*SshAuth)(nil)).Elem(),
	"SshAuthArgs": reflect.TypeOf((*SshAuthArgs)(nil)).Elem(),
	"SshClientArgs": reflect.TypeOf((*SshClientArgs)(nil)).Elem(),
	"StatusLine": reflect.TypeOf((*StatusLine)(nil)).Elem(),
}

var Functions = map[string]reflect.Value{
	"NewSshAuth": reflect.ValueOf(NewSshAuth),
	"NewSshClient": reflect.ValueOf(NewSshClient),
	"SshAuthenticate": reflect.ValueOf(SshAuthenticate),
}

var Variables = map[string]reflect.Value{
}

var Consts = map[string]reflect.Value{
	"DefaultKeyFile": reflect.ValueOf(DefaultKeyFile),
	"DefaultPassword": reflect.ValueOf(DefaultPassword),
	"DefaultSshHost": reflect.ValueOf(DefaultSshHost),
	"DefaultSshPort": reflect.ValueOf(DefaultSshPort),
	"DefaultStatusLineUpdateDelay": reflect.ValueOf(DefaultStatusLineUpdateDelay),
	"DefaultUsername": reflect.ValueOf(DefaultUsername),
	"SshHostPrivateKey": reflect.ValueOf(SshHostPrivateKey),
	"SshHostPublicKey": reflect.ValueOf(SshHostPublicKey),
}

