// Code generated by github.com/gearboxworks/buildtool DO NOT EDIT.

package toolCopy

import "reflect"

var Types = map[string]reflect.Type{
	"MethodFunc": reflect.TypeOf((*MethodFunc)(nil)).Elem(),
	"OsCopyGetter": reflect.TypeOf((*OsCopyGetter)(nil)).Elem(),
	"PathArray": reflect.TypeOf((*PathArray)(nil)).Elem(),
	"State": reflect.TypeOf((*State)(nil)).Elem(),
	"ToolOsCopy": reflect.TypeOf((*ToolOsCopy)(nil)).Elem(),
	"TypeCopyMethod": reflect.TypeOf((*TypeCopyMethod)(nil)).Elem(),
	"TypeCopyMethods": reflect.TypeOf((*TypeCopyMethods)(nil)).Elem(),
	"TypeOsCopy": reflect.TypeOf((*TypeOsCopy)(nil)).Elem(),
	"TypeOsCopyPaths": reflect.TypeOf((*TypeOsCopyPaths)(nil)).Elem(),
}

var Functions = map[string]reflect.Value{
	"New": reflect.ValueOf(New),
	"NewCopyMethod": reflect.ValueOf(NewCopyMethod),
	"ReflectState": reflect.ValueOf(ReflectState),
	"ReflectToolOsCopy": reflect.ValueOf(ReflectToolOsCopy),
	"ToolCopyFiles": reflect.ValueOf(ToolCopyFiles),
	"ToolCopyRsync": reflect.ValueOf(ToolCopyRsync),
}

var Variables = map[string]reflect.Value{
	"GetTools": reflect.ValueOf(&GetTools),
}

var Consts = map[string]reflect.Value{
	"ConstMethodCp": reflect.ValueOf(ConstMethodCp),
	"ConstMethodCpio": reflect.ValueOf(ConstMethodCpio),
	"ConstMethodDefault": reflect.ValueOf(ConstMethodDefault),
	"ConstMethodRsync": reflect.ValueOf(ConstMethodRsync),
	"ConstMethodSftp": reflect.ValueOf(ConstMethodSftp),
	"ConstMethodTar": reflect.ValueOf(ConstMethodTar),
	"ToolPrefix": reflect.ValueOf(ToolPrefix),
}

