// Code generated by github.com/newclarity/PackageReflect DO NOT EDIT.

package hosters

import "reflect"

var Types = map[string]reflect.Type{
	"IndexHoster": reflect.TypeOf((*IndexHoster)(nil)).Elem(),
	"Object": reflect.TypeOf((*Object)(nil)).Elem(),
}

var Functions = map[string]reflect.Value{
	"NewObject": reflect.ValueOf(NewObject),
}

var Variables = map[string]reflect.Value{
}

var Consts = map[string]reflect.Value{
}

