// Code generated by github.com/gearboxworks/buildtool DO NOT EDIT.

package cmd

import "reflect"

var Types = map[string]reflect.Type{
	"CrawlArgs": reflect.TypeOf((*CrawlArgs)(nil)).Elem(),
}

var Functions = map[string]reflect.Value{
}

var Variables = map[string]reflect.Value{
	"CrawlCmd": reflect.ValueOf(&CrawlCmd),
	"RootCmd": reflect.ValueOf(&RootCmd),
}

var Consts = map[string]reflect.Value{
}

