// Code generated by github.com/ungerik/pkgreflect DO NOT EDIT.

package gearConfig

import "reflect"

var Types = map[string]reflect.Type{
	"GearArgs": reflect.TypeOf((*GearArgs)(nil)).Elem(),
	"GearBuild": reflect.TypeOf((*GearBuild)(nil)).Elem(),
	"GearCommands": reflect.TypeOf((*GearCommands)(nil)).Elem(),
	"GearConfig": reflect.TypeOf((*GearConfig)(nil)).Elem(),
	"GearConfigs": reflect.TypeOf((*GearConfigs)(nil)).Elem(),
	"GearEnv": reflect.TypeOf((*GearEnv)(nil)).Elem(),
	"GearExtensions": reflect.TypeOf((*GearExtensions)(nil)).Elem(),
	"GearMeta": reflect.TypeOf((*GearMeta)(nil)).Elem(),
	"GearPorts": reflect.TypeOf((*GearPorts)(nil)).Elem(),
	"GearProject": reflect.TypeOf((*GearProject)(nil)).Elem(),
	"GearRun": reflect.TypeOf((*GearRun)(nil)).Elem(),
	"GearVersion": reflect.TypeOf((*GearVersion)(nil)).Elem(),
	"GearVersions": reflect.TypeOf((*GearVersions)(nil)).Elem(),
}

var Functions = map[string]reflect.Value{
	"New": reflect.ValueOf(New),
}

var Variables = map[string]reflect.Value{
}

var Consts = map[string]reflect.Value{
	"DefaultCommandName": reflect.ValueOf(DefaultCommandName),
	"onlyOnce": reflect.ValueOf(onlyOnce),
}

