// Code generated by github.com/ungerik/pkgreflect DO NOT EDIT.

package toolGitHub

import "reflect"

var Types = map[string]reflect.Type{
	"TypeGetRepositories": reflect.TypeOf((*TypeGetRepositories)(nil)).Elem(),
	"TypeGetRepository": reflect.TypeOf((*TypeGetRepository)(nil)).Elem(),
	"TypeGitHub": reflect.TypeOf((*TypeGitHub)(nil)).Elem(),
}

var Functions = map[string]reflect.Value{
	"HelperGitHubGetBranch": reflect.ValueOf(HelperGitHubGetBranch),
	"HelperGitHubGetOrganization": reflect.ValueOf(HelperGitHubGetOrganization),
	"HelperGitHubLogin": reflect.ValueOf(HelperGitHubLogin),
	"New": reflect.ValueOf(New),
}

var Variables = map[string]reflect.Value{
	"GetHelpers": reflect.ValueOf(&GetHelpers),
}

var Consts = map[string]reflect.Value{
	"HelperPrefix": reflect.ValueOf(HelperPrefix),
	"OnlyOnce": reflect.ValueOf(OnlyOnce),
}

